apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-m4bd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0070-tenant/tkrw-pr712-0075-0070-app/devfile-sample-m4bd@sha256:a0695dff3307dd4573e44816cb1ae8f1d26743551ed64ad0030920f0817ebaee
        name: my-nodejs
        resources: {}
status: {}
